### ISSUE TITLE
Spike: Investigate Cloud Manager

### ISSUE THREAD

**Issue by mollyaljenkins** [aemsites/volvotrucks-na#39]
### Description

Related to the [linked ](https://ncchat.slack.com/archives/C04P8KH8C4D/p1728983649096709)discussion, an investigation of onboarding to Cloud Manager for future roadmap planning is required. 
We need to investigate the abilities and capabilities of Cloud Manager for our websites. We need to understand how it integrates with EDS and how it can support content editors and developers.

### Goal/Objectives
Understand Cloud Manager functionality within EDS, how it can be integrated with GitHub, benefits and requirements for its implementation.

### Tasks

- [ ] Review Cloud Manager documentation for EDS
- [ ] Understand its integration with GitHub
- [ ] Identify limitations
- [ ] Recommendations for next steps

### Deliverable
- Brief documentation/report of the findings.
- Actionable recommendations.
- Relevant links to the documentation consulted.

### Additional Notes
Confirm whether licensing is needed.

### Links 
[https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implem[…]e-delivery-sites/introduction-to-edge-delivery-services](https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/implementing/using-cloud-manager/edge-delivery-sites/introduction-to-edge-delivery-services)

**Comment by BeckyMedlin** [comment]
Dependent on Adobe @dkuntze

**Comment by bouchriy** [comment]
This issue has been migrated to Azure DevOps: https://dev.azure.com/volvo-digital-experience/DEX Platform/_workitems/edit/131024
