### ISSUE TITLE
FR: Adapting Press Releases to Use Pagination from Article Cards

### ISSUE THREAD

**Issue by mollyaljenkins** [aemsites/volvotrucks-na#43]
Following the development of pagination from aemsites/vg-volvotrucks-us#602 as a User I want to be able to use the same pagination feature on the press releases page from Volvo Trucks, so that I can navigate through press releases in a condensed way. 

### User AC
- [ ] Pagination behaves the same as it does on aemsites/vg-volvotrucks-us#602 
- [ ] Buttons are available to navigate forward and backward on the page

### Editor AC
- [ ] Aria labels should be editable in the placeholder.xlsx file. See #56 
- [ ] The text for the aria labels is available [here](https://volvoexperincesystem.z6.web.core.windows.net/?path=/docs/web-components-pagination--docs). See #56 
- [ ] The pagination should display a maximum of 7 pages. If there are more than 7, one or two ellipses will appear within the pagination. For details on how this functionality works, please refer to [this page](https://developer.designsystem.volvogroup.com/?path=/docs/web-components-pagination--docs).

### Non Functional AC
- [ ] The code developed by @amglebihan for aemsites/vg-volvotrucks-us#602 is reused for the press release page
- [ ] The current pagination in the press release page needs to be reviewed and the pagination code from aemsites/vg-volvotrucks-us#602 needs to be adjusted to accommodate 

### Notes

Volvo pagination
https://volvoexperincesystem.z6.web.core.windows.net/?path=/docs/web-components-pagination--docs

- This ticket will be addressed after we conclude the work on the bugs found in the block (Santi will share the ticket for it).

### Technical details
Provide semantics, focus on accessibility things like aria-current="page"
### Attachment / link to Figma
image
- Figma Design:
Desktop/Tablet: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1590%3A21691&mode=dev
Mobile: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1636%3A26829&mode=dev

### Volvo Core Design Kit
https://www.figma.com/file/3NXBS8NFxn7TU0lvNDND7f/BETA---Volvo-Core-Design-Kit?type=design&node-id=28027-71762&mode=design&t=xY5KLIjUP1enK6ZY-4
https://volvoexperincesystem.z6.web.core.windows.net/?path=/docs/web-components-pagination--docs
https://www.volvogroup.com/experiencesystem/en/#/brand/615bfcc428c818001105b4e3/61a0de32a7047974164f01dd/6230544937a675408d840ec2

**Comment by AsmitKMishra** [comment]
Testing Completed. Feature works as expected, fulfills the acceptance criteria and follows the figma design.

<img width="955" alt="Image" src="https://github.com/user-attachments/assets/e16c194f-4a52-4b83-bb71-c31ba016788c" />
