### ISSUE TITLE
Checklist: Helix 5 Upgrade Tasks

### ISSUE THREAD

**Issue by mollyaljenkins** [aemsites/volvotrucks-na#47]
### Helix 5 Upgrade Tasks
- [x] MackTrucks - Testing Search ingestion in new v5 mono-repos  @netmanito @jonatan-lledo-netcentric 
- [x] VolvoTrucks - Testing Search ingestion in new v5 mono-repos  @netmanito @jonatan-lledo-netcentric 
- [x] Provide access to configuration service API (so that other team members can check if configs are ok) @manuel-vara 
- [x] Test Check sitemap.xml picks up updates of pages published/unpublished (waiting on response from @dkuntze on unpublish)
- [x] Update AEM CLI to latest version (all dev team)

### Next Step
- [x] Testing Search results @netmanito @manuel-vara @jonatan-lledo-netcentric (dependent on Search ingestion to be completed https://github.com/hlxsites/vg-volvotrucks-us/issues/755)
- [x] Post GoLive: Test robots.txt is correct (same as we have now) dependent on once the switch to prod origin is done @manuel-vara 
- [x] aemsites/volvotrucks-na#26 @netmanito
