### ISSUE TITLE
NFR: Update AEM Sidekick Library 

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/volvotrucks-na#58]
### Summary

The AEM Sidekick library blocks do not currently comply with the new Helix 5 requirements for buttons, links, and other elements. This is causing confusion among content editors who are copying and pasting blocks from the library, leading to unexpected behavior in pre-production environments.

### Priority

Medium

### Description

The following blocks in the AEM library are to be updated in accordance with AC below, in addition, all existing blocks are to be checked that they are documented and available in the sidekick library.

### Acceptance Criteria 

- [x] The below list of blocks are documented and comply with the Helix 5 upgrade
- [x] All blocks are checked to make sure they are available in the sidekick library
- [x] [The library metadata block is checked for each block](https://github.com/hlxsites/vg-volvotrucks-us/issues/567) 
    - Known missing: truck carousel

The following blocks currently in the AEM Sidekick library need improved documentation corrections to meet the new Helix 5 block requirements:

V1:
- [x] Carousel - AEM Library preview has buttons, they do not appear in the doc however
- [x] Carousel Grid - AEM Library preview has buttons, they do not appear in the doc however
- [x] Document list - buttons don't work
- [x] Get an Offer - buttons don't work
- [x] Key Facts - Icons form two columns instead of 3 and are low res
- [x] video-link - nothing appears, doesn't work at all

V2:
- [x] V2 Banner
  - some buttons are broken displaying :ARROW-RIGHT: in the button text
  - some blocks have 3 buttons showing when only should be 2. 
  - All dark and light themes are named incorrectly. The blocks with (dark) in the name all have white text instead of black, and the (light) themed block names all have black text instead of white - all need to be re-named to be correct for dark to display black text/button and light to display white text/button
  - With centered text - The description of available options should be displayed below the block preview rather than above it. Additionally, when a content editor clicks to copy a block from the library, only the block itself should be copied, without including the options text.
- [x] V2 Content Card (images grid, images grid masonry) - When the editor copies the block from library, the Library Metadata is included which breaks the block. Only the block itself should be copied, and the library metadata description should only be viewed in the library for reference. 
- [x] V2 Content Carousel - The block appears to be broken in the library and does not match the version in production.
- [x] V2 Embed - Nothing works. Should we remove this from the block library?
- [x] V2-stories-carousel - no block appears in the library as a preview, but when you copy it from library it does seem to work as expected. Need to update the block preview to work. Should also add description in the block library to explain this block dynamically pulls in the articles and displaying the articles cannot be content authorable. 
- [x] V2 Feature Carousel - icons are not appearing in any of the first 3 examples and should be present to give the content editor an example of how to use icons. 
- [x] V2 Hero (centered, dark) - video (assets) - this is broken and needs to be fixed. All other hero block examples are working as expected. 
- [x] V2 Key Facts - block seems to be broken in library. The videos don't always work, and the text has too much space between the line items. Should look as it does on production here - https://www.volvotrucks.us/trucks/all-new-vnl/#powertrain
- [x] V2 Media Gallery - block is working but in the description in the library it says "scroll down to test video block" and there is no video. Please remove this text as it is confusing to the content editors. 
- [x] V2 Media with Text - Video with Poster. The very last example is broken. Also, the Media with text - gallery of media content is supposed to turn the media content into a gallery, but it just seems to stack two images on top of each other and seems not to behave as a gallery should. 
- [x] V2-recommendations - doesn't work. Only shows heading "related stories" and no articles appear. 
- [x] V2 Tabbed Carousel - In the sixth option for (columns), the two buttons lack adequate spacing between them. Should this block only accept one button? This could be confusing for content editors, especially since the same block name appears in the eighth example, which uses a hyperlink instead of a button. Clear guidance on which option content editors should follow is needed. Also, there is an "Unnamed Item" below it that doesn't display anything and should be removed. 

### Out of Scope

- [ ] aemsites/volvotrucks-na#32
- [ ] aemsites/volvotrucks-na#31
- [ ] aemsites/volvotrucks-na#30
- [ ] aemsites/volvotrucks-na#29

### Value creation

EX improvement, Maintainability & scalability

### Cost of fixing

Low cost

### Technical complexity

S

### References

https://github.com/hlxsites/vg-macktrucks-com/issues/783

[AEM Block Troubleshooting.xlsx](https://github.com/user-attachments/files/16850870/AEM.Block.Troubleshooting.xlsx)
