### ISSUE TITLE
Template: Magazine Article

### ISSUE THREAD

**Issue by shirin27** [aemsites/volvotrucks-na#65]
### Description
As a content author, I want a quick way to create new articles from a template, so I don't have to add every component used on an article manually.

The scope of this issue is to create the template, every block contained in this template has a separate issue for its development. 

### Acceptance Criteria
- [ ] Magazine Article template is available for authors to use and is added to the AEM Sidekick library, which contains the basic structure and blocks that all Volvo Magazine Articles share.
- [ ] The Magazine Article template contains all of the following elements (in a general order of priority):
  - [ ]  aemsites/volvotrucks-na#33 
  - [x]  aemsites/vg-volvotrucks-us#633 (priority 2) _Planned for 24C - Sprint 3_
  - [x]  aemsites/vg-volvotrucks-us#634 (priority 2) _Planned for 24C - Sprint 3_
  - [x]  aemsites/vg-volvotrucks-us#541 (priority 2) _Planned for 24C - Sprint 4_) **has dependency on aemsites/vg-volvotrucks-us#545** (priority 2) _Planned for 24C - Sprint 5_
  - [x]  aemsites/vg-volvotrucks-us#540 (priority 3) _Planned for 24C - Sprint 4_
  - [x]  aemsites/vg-volvotrucks-us#553 
  - [x] aemsites/vg-volvotrucks-us#635 
  - [x] V2 newsletter (https://go.pardot.com/l/1038333/2023-09-06/43jv | Subscribe for the latest from Volvo Trucks) - existing block
  

### Figma Links

Desktop/Tablet: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1574%3A20616&mode=dev

Mobile: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1602%3A25309&mode=dev

Desktop: 

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/158284953/aafd53d8-fc89-4248-9014-8bd0130b41f0)

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/158284953/e3a817db-f261-446c-ba40-7afaa81cbf86)

**Comment by amglebihan** [comment]
The template is defined on [this page](this page) and can be viewed [here](https://develop--volvotrucks-us--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template).

**Comment by AsmitKMishra** [comment]
Testing Completed. Fulfils acceptance criteria.
