### ISSUE TITLE
Search Checklist: Final Steps Volvo Magazine

### ISSUE THREAD

**Issue by mollyaljenkins** [aemsites/volvotrucks-na#91]
To complete Search functionalities the following out of scope items from ticket #50 (@netmanito 's BE work) are listed below as documentation. 

**Content**
- [x]  Updating pages to support the Search for new pages @Kannan-CM

**Back End**
- [x]  Adjust search to have the AEM repo as the origin @netmanito @manuel-vara
- [x]  https://github.com/aemsites/volvotrucks-na/issues/40
- [x]  Check macktrucks helix5 helix-query.yaml for search @manuel-vara @netmanito
- [x]  https://github.com/aemsites/volvotrucks-na/issues/25

**Front End Styling**
- [x] https://github.com/aemsites/volvotrucks-na/issues/27
- [x]  https://github.com/aemsites/volvotrucks-na/issues/33 
- [x] Implement search bar in #65 
- [x] https://github.com/aemsites/volvotrucks-na/issues/122

**Testing**
- [x]  https://github.com/aemsites/volvotrucks-na/issues/24

**Comment by Kannan-CM** [comment]
This is completed.

**Comment by AsmitKMishra** [comment]
Testing Completed.
